# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesquisa',
            old_name='codigo',
            new_name='curso',
        ),
    ]
