# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_auto_20161130_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='questao9',
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='questao8',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], max_length=1),
        ),
    ]
